import { useState, useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Typography, Input, Button, Spin, message, InputNumber, Card, Space } from 'antd'
import { FilePptOutlined, CodeOutlined, EditOutlined } from '@ant-design/icons'
import { llmService } from '../../services/llmService'
import MarkdownRenderer from '../../components/MarkdownRenderer'
import VoiceInput from '../../shared/VoiceInput'

const { Title, Text } = Typography
const { TextArea } = Input

function PptOutlinePage() {
  const [searchParams] = useSearchParams()
  const presetSlides = parseInt(searchParams.get('slides') || '') || 0
  const presetStyle = searchParams.get('style') || ''
  const presetTopic = searchParams.get('topic') || ''

  const [input, setInput] = useState(presetTopic || '')
  const [slideCount, setSlideCount] = useState(presetSlides || 12)
  const [styleText, setStyleText] = useState(presetStyle)
  const [output, setOutput] = useState('')
  const [editing, setEditing] = useState(false)
  const [downloading, setDownloading] = useState<'pptx' | 'html' | null>(null)
  const [loading, setLoading] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false)

  // Auto-generate when params are provided via AI (only once)
  useEffect(() => {
    if ((presetSlides || presetStyle || presetTopic) && !autoGenerated) {
      setAutoGenerated(true)
      const allParts: string[] = []
      const topic = input || 'PPT'
      if (presetSlides) allParts.push(`${presetSlides} slides 頁`)
      if (presetStyle) allParts.push(presetStyle)
      setLoading(true)
      llmService.call('/api/ppt-outline/run', { text: topic, extra_context: allParts.join(', ') })
        .then((r: any) => setOutput(r.data.result))
        .catch(() => message.error('生成失败'))
        .finally(() => setLoading(false))
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const buildExtra = () => { const p: string[] = []; if (slideCount) p.push(`${slideCount} slides 頁`); if (styleText.trim()) p.push(styleText.trim()); return p.join(', ') }

  const handleRun = async () => {
    if (!input.trim()) return; setLoading(true)
    try { const r: any = await llmService.call('/api/ppt-outline/run', { text: input, extra_context: buildExtra() }); setOutput(r.data.result); setEditing(false) } catch { message.error('Failed 調用失敗') } finally { setLoading(false) }
  }

  const downloadPptx = async () => {
    setDownloading('pptx')
    try {
      const r = await fetch('/api/ppt-outline/generate-pptx', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ outline: output, slide_count: slideCount }) })
      if (!r.ok) throw new Error('Failed')
      const blob = await r.blob(); const url = URL.createObjectURL(blob)
      const a = document.createElement('a'); a.href = url; a.download = 'presentation.pptx'; a.click(); URL.revokeObjectURL(url)
      message.success('PPTX downloaded 已下載')
    } catch { message.error('Generation failed 生成失敗') } finally { setDownloading(null) }
  }

  const downloadHtml = async () => {
    setDownloading('html')
    try {
      const r = await fetch('/api/ppt-outline/generate-html', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ outline: output }) })
      if (!r.ok) throw new Error('Failed')
      const blob = await r.blob(); const url = URL.createObjectURL(blob)
      const a = document.createElement('a'); a.href = url; a.download = 'presentation.html'; a.click(); URL.revokeObjectURL(url)
      message.success('HTML downloaded — double-click to present 已下載，雙擊即可全屏演示')
    } catch { message.error('Generation failed 生成失敗') } finally { setDownloading(null) }
  }

  return (
    <div className="tool-header" style={{ maxWidth: 900, margin: '0 auto' }}>
      <Title level={3}><FilePptOutlined /> PPT / HTML Generator 簡報生成</Title>
      <Text type="secondary">Enter a topic — AI generates a structured outline, then download as PPTX or reveal.js HTML  |  輸入主題，AI 生成結構化大綱，一鍵下載 PPTX 或 HTML 演示文稿</Text>
      <VoiceInput onResult={(text) => setInput(text)} />
      <TextArea rows={3} value={input} onChange={e => setInput(e.target.value)} placeholder="Enter a topic, e.g. Q3 2026 Work Report 輸入主題..." style={{ borderRadius: 10, marginTop: 16 }} />
      <div style={{ marginTop: 12, display: 'flex', gap: 18, alignItems: 'center', flexWrap: 'wrap' }}>
        <Space><Text>Slides 頁數:</Text><InputNumber min={1} max={50} value={slideCount} onChange={v => setSlideCount(v || 12)} style={{ width: 80, borderRadius: 8 }} /></Space>
        <Space style={{ flex: 1 }}><Text>Style 風格:</Text><Input placeholder="Minimal, data-driven... 極簡、數據驅動..." value={styleText} onChange={e => setStyleText(e.target.value)} style={{ width: 240, borderRadius: 8 }} /></Space>
      </div>
      <div style={{ marginTop: 14 }}><Button type="primary" onClick={handleRun} loading={loading} style={{ borderRadius: 100, paddingLeft: 24, paddingRight: 24 }}>Generate Outline 生成大綱</Button></div>
      {loading && <Spin style={{ margin: '28px auto', display: 'block' }} />}
      {output && (
        <Card style={{ marginTop: 20, borderRadius: 14, border: 'none' }} styles={{ body: { padding: '20px 26px' } }}>
          <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 12 }}><Button size="small" icon={<EditOutlined />} onClick={() => setEditing(!editing)} style={{ borderRadius: 100 }}>{editing ? 'Preview 預覽' : 'Edit 編輯'}</Button></div>
          {editing ? <TextArea rows={22} value={output} onChange={e => setOutput(e.target.value)} style={{ borderRadius: 8 }} /> : <MarkdownRenderer content={output} />}
          <div style={{ marginTop: 18, textAlign: 'center', display: 'flex', justifyContent: 'center', gap: 14 }}>
            <Button type="primary" size="large" icon={<FilePptOutlined />} loading={downloading === 'pptx'} onClick={downloadPptx} style={{ borderRadius: 100, paddingLeft: 24, paddingRight: 24 }}>Download PPTX 下載 PPTX</Button>
            <Button size="large" icon={<CodeOutlined />} loading={downloading === 'html'} onClick={downloadHtml} style={{ borderRadius: 100, paddingLeft: 24, paddingRight: 24 }}>Download HTML 下載 HTML</Button>
          </div>
        </Card>
      )}
    </div>
  )
}

export default PptOutlinePage
